"""create eligibility_checks and prior_auth_checks tables

Revision ID: 143eb2c881ff
Revises: 
Create Date: 2026-03-13 14:44:32.948966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143eb2c881ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eligibility_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('check_id', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('patient_first_name', sa.String(length=100), nullable=False),
    sa.Column('patient_last_name', sa.String(length=100), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('patient_dob', sa.String(length=20), nullable=True),
    sa.Column('member_id', sa.String(length=100), nullable=True),
    sa.Column('payer_id', sa.String(length=50), nullable=True),
    sa.Column('payer_name', sa.String(length=200), nullable=True),
    sa.Column('provider_npi', sa.String(length=20), nullable=True),
    sa.Column('provider_name', sa.String(length=200), nullable=True),
    sa.Column('service_type_code', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('annual_deductible', sa.Float(), nullable=True),
    sa.Column('annual_deductible_max', sa.Float(), nullable=True),
    sa.Column('out_of_pocket', sa.Float(), nullable=True),
    sa.Column('out_of_pocket_max', sa.Float(), nullable=True),
    sa.Column('copay', sa.Float(), nullable=True),
    sa.Column('coinsurance', sa.Float(), nullable=True),
    sa.Column('prior_auth_required', sa.Boolean(), nullable=True),
    sa.Column('coverage_start', sa.String(length=20), nullable=True),
    sa.Column('coverage_end', sa.String(length=20), nullable=True),
    sa.Column('plan_name', sa.String(length=200), nullable=True),
    sa.Column('group_number', sa.String(length=50), nullable=True),
    sa.Column('plan_number', sa.String(length=50), nullable=True),
    sa.Column('carrier_name', sa.String(length=200), nullable=True),
    sa.Column('subscriber_name', sa.String(length=200), nullable=True),
    sa.Column('patient_dob_from_payer', sa.String(length=20), nullable=True),
    sa.Column('patient_gender', sa.String(length=10), nullable=True),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('coverage_status', sa.String(length=50), nullable=True),
    sa.Column('claims_address', sa.Text(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('total_errors', sa.Integer(), nullable=False),
    sa.Column('total_warnings', sa.Integer(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('run_date', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_checks_check_id'), 'eligibility_checks', ['check_id'], unique=True)
    op.create_table('prior_auth_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pa_id', sa.String(length=20), nullable=False),
    sa.Column('patient_first_name', sa.String(length=100), nullable=False),
    sa.Column('patient_last_name', sa.String(length=100), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('patient_dob', sa.String(length=20), nullable=True),
    sa.Column('member_id', sa.String(length=100), nullable=True),
    sa.Column('payer_id', sa.String(length=50), nullable=True),
    sa.Column('payer_name', sa.String(length=200), nullable=True),
    sa.Column('provider_npi', sa.String(length=20), nullable=True),
    sa.Column('provider_name', sa.String(length=200), nullable=True),
    sa.Column('service_type_code', sa.String(length=10), nullable=True),
    sa.Column('diagnosis_code', sa.String(length=20), nullable=True),
    sa.Column('procedure_code', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('auth_number', sa.String(length=100), nullable=True),
    sa.Column('eligibility_check_id', sa.String(length=20), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('run_date', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prior_auth_checks_pa_id'), 'prior_auth_checks', ['pa_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prior_auth_checks_pa_id'), table_name='prior_auth_checks')
    op.drop_table('prior_auth_checks')
    op.drop_index(op.f('ix_eligibility_checks_check_id'), table_name='eligibility_checks')
    op.drop_table('eligibility_checks')
    # ### end Alembic commands ###
